# Generated by Django 4.0.5 on 2022-06-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wendy_store', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='wendy_store/images/%Y/%m/%d/'),
        ),
    ]
